web:
  build: .
  command: python wsgi.py
  ports:
    - "21050:21050"
  volumes:
    - .:/code
  links:
    - redis
  environment:
    - IMPALA_HOST
    - IMPALA_PORT
    - SECURITY_TOKEN
redis:
  image: redis
